name: Main

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.16

      - name: Install projectl
        run: cd ; go get github.com/aaronellington/projectl

      - name: Check out code
        uses: actions/checkout@v2

      - name: Build
        run: make full git-change-check projectl git-change-check
